### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by xby1510921311** [fsx950223/mobilenetv2-yolov3#14]
Hi,what should I do to solve "AttributeError: module 'tensorflow.python.data' has no attribute 'experimental'" ,this problem.Is it related to my version?I tried tensorflow 1.7.0 and 1.6.0 ,It doesn't work.

**Comment by fsx950223** [comment]
Please use tensorflow1.13.1

**Comment by xby1510921311** [comment]
谢谢您，还有个问题，train.py中  train_dataset_path val_dataset_path这两个路径是训练图片和验证图片的路径吗，也就是需要把训练集和验证集存在两个文件夹中吗？  
train_dataset_glob val_dataset_glob这两个是把数据集转成tfrecord的同一个文件吗?

**Comment by fsx950223** [comment]
> 谢谢您，还有个问题，train.py中 train_dataset_path val_dataset_path这两个路径是训练图片和验证图片的路径吗，也就是需要把训练集和验证集存在两个文件夹中吗？
> train_dataset_glob val_dataset_glob这两个是把数据集转成tfrecord的同一个文件吗?

It's depend on yourself
