### ISSUE TITLE
What is your training strategy? 

### ISSUE THREAD

**Issue by E12dward** [fsx950223/mobilenetv2-yolov3#2]
What is your training strategy? Just follow the  code here or something else?
How much are your loss and mAP after some epochs on VOC?

**Comment by fsx950223** [comment]
You can download dataset from my google drive and change dataset paths in train.py.
I used VOC 2012 and 2007 train the model.After 100 epochs,loss is 14.7.

**Comment by E12dward** [comment]
我第一次训练时发现stage1 30 epoch结束后loss在20作用，然后stage2 训练15个epoch之后loss为19.33然后看起来就很难进行下去了。我只采用了VOC2007的train部分，并且结果显示mAP只有45%
我应该继续训练下去吗？还是其它地方处理什么问题？请问您的mAP是多少？

**Comment by fsx950223** [comment]
我使用2007 2012一起训练，解冻所有层可以微调到14

**Comment by E12dward** [comment]
你提到过higher accuracy,是指在VOC数据集上比Darknet53_yolov3的表现好吗？另外谢谢您的回答

**Comment by fsx950223** [comment]
那是我们公司的数据集

**Comment by fsx950223** [comment]
你如果还有疑问，你也可以切换到darknet53的backbone，用224进行训练对比

**Comment by fsx950223** [comment]
你可以关掉一些数据增强来获得在pascal数据集上更好的预测效果

**Comment by gzz1529657064** [comment]
> 我第一次训练时发现stage1 30 epoch结束后loss在20作用，然后stage2 训练15个epoch之后loss为19.33然后看起来就很难进行下去了。我只采用了VOC2007的train部分，并且结果显示mAP只有45%
> 我应该继续训练下去吗？还是其它地方处理什么问题？请问您的mAP是多少？



> 你可以关掉一些数据增强来获得在pascal数据集上更好的预测效果



> 你可以关掉一些数据增强来获得在pascal数据集上更好的预测效果

作者，你好。我按照keras-yolov3的复现步骤，但是出了问题。在执行python yolo_video.py --image 时报错。有些问题想请教你。我的微信号：wxid_cbjyy2ydd0j422

**Comment by gzz1529657064** [comment]
作者，你好。我按照keras-yolov3的复现步骤，但是出了问题。在执行python yolo_video.py --image 时报错。有些问题想请教你。我的微信号：wxid_cbjyy2ydd0j422

**Comment by gzz1529657064** [comment]
> 你可以关掉一些数据增强来获得在pascal数据集上更好的预测效果

作者，你好。我按照keras-yolov3的复现步骤，但是出了问题。在执行python yolo_video.py --image 时报错。有些问题想请教你。我的微信号：wxid_cbjyy2ydd0j422

**Comment by gzz1529657064** [comment]
> 我第一次训练时发现stage1 30 epoch结束后loss在20作用，然后stage2 训练15个epoch之后loss为19.33然后看起来就很难进行下去了。我只采用了VOC2007的train部分，并且结果显示mAP只有45%
> 我应该继续训练下去吗？还是其它地方处理什么问题？请问您的mAP是多少？

你是怎么复现的？能说一下复现过程吗？有些问题想问问你。我的微信号：wxid_cbjyy2ydd0j422

**Comment by shenyingying** [comment]
@ 你的微信号好像搜不到

**Comment by gzz1529657064** [comment]
------------------ 原始邮件 ------------------
发件人: "BlueSandals"<notifications@github.com>;
发送时间: 2019年5月29日(星期三) 下午5:46
收件人: "fsx950223/mobilenetv2-yolov3"<mobilenetv2-yolov3@noreply.github.com>;
抄送: "墨麟非攻"<1529657064@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [fsx950223/mobilenetv2-yolov3] What is your training strategy? (#2)




@ 你的微信号好像搜不到
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.




附件内是我的二维码名片
