### ISSUE TITLE
for the mobilenetv2 backnone, r.1.14 cannot load weights file from older version

### ISSUE THREAD

**Issue by hejinIzhanghao** [fsx950223/mobilenetv2-yolov3#25]
in r1.14, when I tried to load a weights file from earlier version, it reported:
You are trying to laod a weight file containning 121 layers into a model with 169 layers.

**Comment by hejinIzhanghao** [comment]
hi, @fsx950223 
for the weights file, is the latest version compabile with the last one?

**Comment by fsx950223** [comment]
No, you need to train model with latest version

2019年7月23日 下午8:21，hejinIzhanghao <notifications@github.com>写道：

hi, @fsx950223<https://github.com/fsx950223>
for the weights file, is the latest version compabile with the last one?

**Comment by hejinIzhanghao** [comment]
OK. one more question, where to get the pretained model or backbone model for latest mobilenetv2 and efficientnet?

**Comment by fsx950223** [comment]
> OK. one more question, where to get the pretained model or backbone model for latest mobilenetv2 and efficientnet?

It will download model automatically when you use imagenet as backbone model path
