### ISSUE TITLE
multi-gpu error

### ISSUE THREAD

**Issue by hejinIzhanghao** [fsx950223/mobilenetv2-yolov3#26]
Hi @fsx950223 

I got an error message when using multi-gpu in tf 1.14.0
`
Registered kernels:
 <no registered kernels>
 [[NcclAllReduce]] [Op:__inference__all_reduce_39259]
`
But it worked with single gpu when I commented out the "with strategy.scope():"

Anybody got the same issue?

**Comment by fsx950223** [comment]
please install nccl
