### ISSUE TITLE
num = reduce(lambda x, y: x + y, map(lambda file: int(file.split('/')[-1].split('.')[0].split('_')[3]), files))

### ISSUE THREAD

**Issue by ggolkar** [fsx950223/mobilenetv2-yolov3#3]
Hi ,
I am trying to train my custom dataset  using mobilenetv2 backend .
I have set the path and the glob as follows :
   train_dataset_path = 'data2/train'
    val_dataset_path = 'data2/valid'
    train_dataset_glob = 'train.txt'
    val_dataset_glob = 'valid.txt'
 The train txt has this format :img/1.jpg 0.626172,0.419444,0.007031,0.008333,0  0.625391,0.434722,0.005469,0.044444,0 0.633594,0.427083,0.003125,0.020833,0
However, I have encountered the following issue in data.py  :
   
 num = reduce(lambda x, y: x + y, map(lambda file: int(file.split('/')[-1].split('.')[0].split('_')[3]), files))
list index out of range error .
It does not have this error with  .tfrecords
Could you please help me with this ?
Thanks .

**Comment by fsx950223** [comment]
Please format file name like <name>_<number>.<extension>

**Comment by ggolkar** [comment]
Thanks alot for your prompt reply and the guidance .The problem was solved. However,I have now encountered another one 
I keep getting the following error :
Epoch 1/10
249/250 [============================>.] - ETA: 7s - loss: 152.7889 
2019-04-19 16:36:36.388052: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at strided_slice_op.cc:106
: Invalid argument: slice index 1 of dimension 0 out of bounds.
2019-04-19 16:36:36.388052: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at strided_slice_op.cc:106 : Invalid argument: slice index 4 of dimension 0 out of bounds.
2019-04-19 16:36:36.671072: W tensorflow/core/framework/op_kernel.cc:1389] Unknown: InvalidArgumentError: slice index 4 of dimension 0 out of bounds. [Op:StridedSlice] name: strided_slice/

I am just testing it with a small data set without GPU . I was wondering whether you can also help me with this .

Thanks heaps .

**Comment by fsx950223** [comment]
> Thanks alot for your prompt reply and the guidance .The problem was solved. However,I have now encountered another one
> I keep getting the following error :
> Epoch 1/10
> 249/250 [============================>.] - ETA: 7s - loss: 152.7889
> 2019-04-19 16:36:36.388052: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at strided_slice_op.cc:106
> : Invalid argument: slice index 1 of dimension 0 out of bounds.
> 2019-04-19 16:36:36.388052: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at strided_slice_op.cc:106 : Invalid argument: slice index 4 of dimension 0 out of bounds.
> 2019-04-19 16:36:36.671072: W tensorflow/core/framework/op_kernel.cc:1389] Unknown: InvalidArgumentError: slice index 4 of dimension 0 out of bounds. [Op:StridedSlice] name: strided_slice/
> 
> I am just testing it with a small data set without GPU . I was wondering whether you can also help me with this .
> 
> Thanks heaps .

Please check your .txt file's format follows ```<image_path> <xmin> <xmax> <ymin> <ymax> <label>```

**Comment by ggolkar** [comment]
Thanks a lot for the help. It is solved .

**Comment by Zanderzt** [comment]
Hello,first thank you for your code,I want ask the format <name>_<number>.<extension>,what is extension,could you support some samples.Thanks!
