### ISSUE TITLE
NotFoundError: Resource localhost/logdir:

### ISSUE THREAD

**Issue by khbadii** [fsx950223/mobilenetv2-yolov3#4]
Hi
I tried to run the 'train.py' with my data, but it showed below error during epoch 11/20:

File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.NotFoundError: Resource localhost/logdir:logs/mobilenetv22019-04-22/class tensorflow::SummaryWriterInterface does not exist. [Op:WriteScalarSummary]
name: epoch_loss/
Please let me know how I can sove the problem.

Regards

**Comment by fsx950223** [comment]
remove tensorboard callback

**Comment by khbadii** [comment]
Thanks. Done.
