### ISSUE TITLE
pretrained model @ pan.baidu.com

### ISSUE THREAD

**Issue by hejinIzhanghao** [fsx950223/mobilenetv2-yolov3#45]
hello @fsx950223 

  drive.google.com搞不定啊，能不能把pretrained model搞一份在百度网盘。

**Comment by HKVINS89757** [comment]
唉 国人的悲哀   自己人搞的东西还要反而外国人更方便一些

**Comment by yujun2019** [comment]
@HKVINS89757  关键是咱们自己人不让你访问别人的网站啊，你搞清楚因果关系

**Comment by HKVINS89757** [comment]
> @HKVINS89757  关键是咱们自己人不让你访问别人的网站啊，你搞清楚因果关系

放到百度网盘腾讯网盘不就行了
