### ISSUE TITLE
error when using BOX_LOSS.MSE

### ISSUE THREAD

**Issue by hejinIzhanghao** [fsx950223/mobilenetv2-yolov3#46]
hello @fsx950223 
  
   Using the lastest version, i got not bad resutls. Thx.

   But when I changed box_loss from GIOU to MSE, i got the error at model.py line 601. it said

> TypeError: Input 'y' of 'Mul' Op has tyep int32 that does not match type float32  of argument 'x'.

  Should there be a type cast? Or I made something wrong?

**Comment by fsx950223** [comment]
There maybe some bugs,you can change code util you can run it. And PR is welcomed
