### ISSUE TITLE
Cannot train good model with r.14 as the last version did

### ISSUE THREAD

**Issue by hejinIzhanghao** [fsx950223/mobilenetv2-yolov3#50]
Hi, @fsx950223 

  I'm using the newest version of codes to train my own model. But with the same dataset and default settings,  the newest version cannot train models as good as the last version did. 
 In the newest version, when setting freeze=true, it run well. But when setting freeze=false, the val-loss went down only for afew epoches, e.g. 4,5. I seemed like the training did not converge. 

  I looked through the codes, but did not find the reason yet.

  There are afew differences between the newst version and before. are they the reasons?
- the network strctures are different
- alittle difference in yolo_loss(). 
the newest version is 
`input_shape = tf.shape(yolo_output)[1:3] * grid_step`
but it was like
`input_shape = tf.shape(yolo_output)[1:3] * 32`
I made the yolo_loss same as before, but it did not work.

any suggestions for this issue?

**Comment by fsx950223** [comment]
How abour mAP

**Comment by IrisDinge** [comment]
> Hi, @fsx950223
> 
> I'm using the newest version of codes to train my own model. But with the same dataset and default settings, the newest version cannot train models as good as the last version did.
> In the newest version, when setting freeze=true, it run well. But when setting freeze=false, the val-loss went down only for afew epoches, e.g. 4,5. I seemed like the training did not converge.
> 
> I looked through the codes, but did not find the reason yet.
> 
> There are afew differences between the newst version and before. are they the reasons?
> 
>     * the network strctures are different
> 
>     * alittle difference in yolo_loss().
>       the newest version is
>       `input_shape = tf.shape(yolo_output)[1:3] * grid_step`
>       but it was like
>       `input_shape = tf.shape(yolo_output)[1:3] * 32`
>       I made the yolo_loss same as before, but it did not work.
> 
> 
> any suggestions for this issue?

HI, i'm asking for help:) did you meet error as following?

Traceback (most recent call last):
  File "main.py", line 170, in <module>
    app.run(main)
  File "./naconda3/envs/kmy37gpu/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "..anaconda3/envs/kmy37gpu/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 136, in main
    train(flags_dict)
  File "../mobilenetv2-yolov3/train.py", line 75, in train
    train_dataset, train_num = train_dataset_builder.build()
TypeError: cannot unpack non-iterable NoneType object


i modified train_dataset, train_num = train_dataset_builder.build() by adding mode=mode=DATASET_MODE.TRAIN in the end, but still occurs this error

Thk U in advanced

**Comment by fsx950223** [comment]
> Hi, @fsx950223
> 
> I'm using the newest version of codes to train my own model. But with the same dataset and default settings, the newest version cannot train models as good as the last version did.
> In the newest version, when setting freeze=true, it run well. But when setting freeze=false, the val-loss went down only for afew epoches, e.g. 4,5. I seemed like the training did not converge.
> 
> I looked through the codes, but did not find the reason yet.
> 
> There are afew differences between the newst version and before. are they the reasons?
> 
> * the network strctures are different
> * alittle difference in yolo_loss().
>   the newest version is
>   `input_shape = tf.shape(yolo_output)[1:3] * grid_step`
>   but it was like
>   `input_shape = tf.shape(yolo_output)[1:3] * 32`
>   I made the yolo_loss same as before, but it did not work.
> 
> any suggestions for this issue?

training strategy has changed.You can try old one to replace cos_lr

**Comment by hejinIzhanghao** [comment]
I tried the reduce_lr in last version, but it didnot work

**Comment by hejinIzhanghao** [comment]
after using reduce_lr and larger batch_size, it converged.
