### ISSUE TITLE
how is the multiscale training implemented?

### ISSUE THREAD

**Issue by hejinIzhanghao** [fsx950223/mobilenetv2-yolov3#57]
@fsx950223 , where are the codes for multiscale training?
  what i found was Dataset::__init__(), that's all?

**Comment by hejinIzhanghao** [comment]
there was Dataset::on_batch_end() to implement multiscale inpu_shape, but not in the master branch now.

**Comment by fsx950223** [comment]
It's not work with MirrorStrategy

hejinIzhanghao <notifications@github.com<mailto:notifications@github.com>> 于2019年9月6日周五 上午9:19写道：

@fsx950223<https://github.com/fsx950223> , where are the codes for multiscale training?
what i found was Dataset::init(), that's all?
