### ISSUE TITLE
how about the 'focal loss'

### ISSUE THREAD

**Issue by hejinIzhanghao** [fsx950223/mobilenetv2-yolov3#64]
hi @fsx950223 
There was 'focal loss' in readme.md @ 407ebe4
how about it ?

**Comment by fsx950223** [comment]
It leads the bad performance and I remove it.

**Comment by hejinIzhanghao** [comment]
In which commit I can find your focal loss implementation?

**Comment by fsx950223** [comment]
99c0ae88df0accbbb69a9c7456c5b747627c3702

**Comment by hejinIzhanghao** [comment]
got it

**Comment by prakharg24** [comment]
To @hejinIzhanghao ,

Did you try out with focal loss again? Did you also get bad results?

To @fsx950223 ,

The commit that you pointed out has focal loss only in the term 'confidence_loss'. Shouldn't it actually be in the term 'class_loss'?
