### ISSUE TITLE
loss中计算best iou为何没有对每张图像单独计算?

### ISSUE THREAD

**Issue by zhen8838** [fsx950223/mobilenetv2-yolov3#65]
作者你好,我发现你将keras-yolo3中的迭代计算batch中每张图像的best iou删除了, 直接计算整个batch预测bbox与整个batch标签bbox的best iou. 

这样不是会导致比如batch中某张图像的预测bbox与另外一张图像的标签bbox的iou分数最高吗?还是你已经在哪里做了一些处理? 

还有你给出的mAp是对test_dataset计算出来的吗?

**Comment by fsx950223** [comment]
你应该是对的。
mAp是用test_dataset计算

**Comment by zhen8838** [comment]
感谢回复, 我还想再请教一个问题, 目前我参考keras yolo3写了[自己yolo](https://github.com/zhen8838/K210_Yolo_framework)

我感觉代码中细节应该没错了, 模型h5是缩小到14mb的, 目测效果还可以。但在测试voc中的mAp只有25，我觉这个模型虽然比较小，但至少也应该mAp能达到40左右。。

所以想请教一下您，训练时或代码中还有哪一些值得注意的细节？或者您训练时提升精度的一些方法？

**Comment by fsx950223** [comment]
预测时候的目标框算法好像是错的

**Comment by fsx950223** [comment]
> 好的，谢谢，我去看看

我的改进方案基本都列举出来了，你可以逐条对比。

**Comment by hejinIzhanghao** [comment]
@zhen8838 ，这是一个bug么？有pr么？

**Comment by fsx950223** [comment]
测了map 基本没区别

hejinIzhanghao <notifications@github.com<mailto:notifications@github.com>> 于 2019年10月28日周一 下午3:11写道：

@zhen8838<https://github.com/zhen8838> ，这是一个bug么？有pr么？

**Comment by zhen8838** [comment]
我看了几个高star的作者的yolo是没有循环计算的, 但gluoncv和star最高的keras-yolo3是做了循环计算的.

**Comment by hejinIzhanghao** [comment]
我遇到了这样一个问题：在我们自己的数据集上训练，pjreddie darknet训练出来的结果比用fsx950223 mobilenetv2-yolov3得到的结果好。我查了几遍代码，也没发现什么问题。其他最大的差别就是optimizer了，这个不好对比。
@zhen8838 有pr发过来看看么？或者把修改的办法发出来

**Comment by hejinIzhanghao** [comment]
@zhen8838 ，你说的问题是在box_giou()么？

**Comment by zhen8838** [comment]
https://github.com/qqwweee/keras-yolo3/blob/e6598d13c703029b2686bc2eb8d5c09badf42992/yolo3/model.py#L388

**Comment by zhen8838** [comment]
作者的代码主要是keras-yolo3里面改过去的,我自己写的是参考keras-yolo3重写的.说实话,我尝试了许多作者的代码,也包括我自己的,都没有darknet的效果.应该还是有些地方和darknet不一样的. 本来我想从gluon cv中移植,但是gluon cv的代码实在太复杂了.

**Comment by hejinIzhanghao** [comment]
@zhen8838 你也遇到一样的问题么？同样的darknet53模型，pjreddie darknet训练出来的结果更好？

**Comment by HKVINS89757** [comment]
看到都是用中文交流 才觉得github正常了，    以前一群中国人用蹩脚的英文不知道交流个啥

**Comment by fsx950223** [comment]
> 我遇到了这样一个问题：在我们自己的数据集上训练，pjreddie darknet训练出来的结果比用fsx950223 mobilenetv2-yolov3得到的结果好。我查了几遍代码，也没发现什么问题。其他最大的差别就是optimizer了，这个不好对比。
> @zhen8838 有pr发过来看看么？或者把修改的办法发出来
你在自己数据集上是不是用了kmeans

**Comment by hejinIzhanghao** [comment]
两个框架用的同样的anchor，都是用kmeans算的

**Comment by hejinIzhanghao** [comment]
@zhen8838 明白你说best iou的意思了。确实如 @fsx950223 所说，差别应该很小

**Comment by zhen8838** [comment]
我的模型是缩小到14mb的,但是mAp比我预想的低很多. 我自己的代码是用imgaug库做的数据增强添加了翻转、平移、缩放、旋转,但我感觉没有多大提升可能是个问题. 在gluon cv里面https://github.com/dmlc/gluon-cv/blob/e69c8a95817cb0b3e020c8e72ef46bd9f90aea9a/gluoncv/data/transforms/presets/yolo.py#L152 就使用了按bbox裁剪、翻转、缩放还有个mixup，这样也才达到darknet的精度。。

**Comment by HKVINS89757** [comment]
你们的loss 到多少啊

**Comment by zhen8838** [comment]
我自己写的代码，精简的模型 val loss大概14。

**Comment by HKVINS89757** [comment]
我的也差不多 但是我觉得是样本的问题，所以我现在在码样本增强的代码

**Comment by zhen8838** [comment]
恩。我loss上面找不到问题了。。。也是在从数据增强考虑

**Comment by zhen8838** [comment]
还有几个超参的问题，正样本的loss权重和负样本loss权重大家一般选多少？ 还有我看这个代码的作者，给wh loss的权重减小了一半。

**Comment by HKVINS89757** [comment]
https://github.com/GuodongQi/yolo3_tensorflow
你们跑过这个吗？我觉得这个好像还不错

**Comment by hejinIzhanghao** [comment]
你们觉得是data aug的问题？ 但是darknet并没有做很多data aug

**Comment by HKVINS89757** [comment]
别人是标准数据集啊 数据足够啊  我跑的是自己的

**Comment by zhen8838** [comment]
这个yolo3 tensorflow，看loss应该是参考的keras yolo3的。无法解决现在的问题。。。

**Comment by hejinIzhanghao** [comment]
@zhen8838 loss计算有超参么？
loss的计算倒是与darknet有一点不一样，
darknet yolo_layer.c：
*(l.cost) = pow(mag_array(l.delta, l.outputs*l.batch), 2);

**Comment by fsx950223** [comment]
```    intersect_mins = tf.maximum(b1_mins, b2_mins)
    intersect_maxes = tf.minimum(b1_maxes, b2_maxes)```
已经用批量计算了每张图的最大值与最小值，所以不需要用循环
