### ISSUE TITLE
 No module named 'yolo3.enum'

### ISSUE THREAD

**Issue by Pangzaijun** [fsx950223/mobilenetv2-yolov3#79]
您好，请问一下 No module named 'yolo3.enum'是什么原因？

**Comment by Pangzaijun** [comment]
经核查代码，yolo3文件夹下为enums

**Comment by fsx950223** [comment]
Change to yolo3.enums

**Comment by Pangzaijun** [comment]
> Change to yolo3.enums

请问一下运行环境是ubuntu18.04吗？还是win10环境下也可以运行呢

**Comment by fsx950223** [comment]
ubuntu18.04
